name: string-syntax
version: 0.1.0
category: Text
synopsis: Prototype for string interpolation.
description: Prototype for string interpolation. See README.md for more details
license: BSD3
license-file: LICENSE.md
author: Brandon Chinn <brandonchinn178@gmail.com>
maintainer: Brandon Chinn <brandonchinn178@gmail.com>

extra-source-files:
  - README.md

github: brandonchinn178/string-syntax

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wnoncanonical-monad-instances

library:
  source-dirs: src
  dependencies:
    - base
    - containers
    - megaparsec
    - text
    - template-haskell
  language: GHC2021

executable:
  source-dirs: exe
  main: Preprocessor.hs
  dependencies:
    - base
    - string-syntax
    - text
  language: GHC2021
